export const LABELS = {
    id: "ID",
    lot: "Lot",
    lat: "Latitude",
    lon: "Longitude",
    dateIn: "Delivery Date Arrival",
    dateOut: "Delivery Date",
    source: "Source",
    target: "Target",
    originalSource: "Original Source",
    originalTarget: "Original Target",
    incoming: "Incoming",
    outgoing: "Outgoing",
    contains: "Contains",
    isMeta: "Is Meta Station",
    contained: "Is Meta Member",
    forward: "Forward Trace",
    backward: "Backward Trace",
    traceType: "Trace Type",
    observed: "Observed",
    outbreak: "Outbreak",
    crossContamination: "Cross Contamination",
    killContamination: "Kill Contamination",
    commonLink: "Common Link",
    score: "Score",
    weight: "Weight",
    anonymisationLabel: "Anonymisation Label",
    anonymizedName: "Anonymized Name",
    name: "Name",
    address: "Address",
    country: "Country",
    typeOfBusiness: "Type of Business",
    selected: "Selected",
    invisible: "Invisible",
    product: "Product",
    amount: "Amount",
    stationLabel: "Station Label",
    deliveryLabel: "Delivery Label",
} as const satisfies Record<string, string>;
