export const SHARED_PROP_LABELS = {
    id: "ID",
    forward: "On Forward Trace",
    backward: "On Backward Trace",
    traceType: "Trace Type",
    observed: "Observed",
    outbreak: "Outbreak",
    commonLink: "Common Link",
    crossContamination: "Cross Contamination",
    killContamination: "Kill Contamination",
    score: "Score",
    weight: "Weight",
    name: "Name",
    selected: "Selected",
    invisible: "Invisible",
} as const satisfies Record<string, string>;

export const STATION_PROP_LABELS = {
    ...SHARED_PROP_LABELS,
    lat: "Latitude",
    lon: "Longitude",
    contains: "Contains",
    isMeta: "Is Meta Station",
    contained: "Is Meta Member",
    anonymizedName: "Anonymized Name",
    address: "Address",
    country: "Country",
    typeOfBusiness: "Type of Business",
    incoming: "Incoming",
    outgoing: "Outgoing",
} as const satisfies Record<string, string>;

export const DELIVERY_PROP_LABELS = {
    ...SHARED_PROP_LABELS,
    lot: "Lot",
    dateIn: "Delivery Date Arrival",
    dateOut: "Delivery Date",
    source: "Source ID",
    target: "Target ID",
    "source.name": "Source",
    "target.name": "Target",
    originalSource: "Original Source",
    originalTarget: "Original Target",
    product: "Product",
    amount: "Delivery Amount",
    amountNumber: "Delivery Amount Number",
    amountUnit: "Delivery Amount Unit",
    lotAmount: "Lot Amount",
} as const satisfies Record<string, string>;

export const RULE_LABELS = {
    outbreak: SHARED_PROP_LABELS.outbreak,
    observed: SHARED_PROP_LABELS.observed,
    forward: "Forward Trace",
    backward: "Backward Trace",
    crossContamination: SHARED_PROP_LABELS.crossContamination,
    killContamination: SHARED_PROP_LABELS.killContamination,
    commonLink: SHARED_PROP_LABELS.commonLink,
    stationSize: STATION_PROP_LABELS.score,
    stationLabel: "Station Label",
    deliveryLabel: "Delivery Label",
    anonymisationLabel: "Anonymisation Label",
} as const satisfies Record<string, string>;
