export enum SERVER_ERROR_CODE {
  INVALID_INPUT = 5,
}

export enum UserValidationErrorCode {
  INVALID_PWD = 'INVALID_PWD',
  INVALID_FIRSTNAME = 'INVALID_FIRSTNAME',
  INVALID_LASTNAME = 'INVALID_LASTNAME',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_GDPRA = 'INVALID_GDPR',
  MISSING_PWD = 'MISSING_PWD',
  MISSING_FIRSTNAME = 'MISSING_FIRSTNAME',
  MISSING_LASTNAME = 'MISSING_LASTNAME',
  MISSING_EMAIL = 'MISSING_EMAIL',
}
